blank_issues_enabled: true
contact_links:
  - name: CSV Manager Documentation
    url: https://github.com/yourusername/csv-manager/wiki
    about: Check out the documentation before submitting an issue
  - name: CSV Manager Discussions
    url: https://github.com/yourusername/csv-manager/discussions
    about: Please ask and answer questions here