name: CSV Manager CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for TypeScript errors
      run: npx tsc --noEmit
      
    - name: Lint files
      run: npm run lint
      
    - name: Build project
      run: npm run build
      
    - name: Run tests
      run: npm test

  verify-version:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Check VERSION file exists
      run: test -f VERSION || (echo "Error: VERSION file not found" && exit 1)
      
    - name: Check CHANGELOG.md exists
      run: test -f CHANGELOG.md || (echo "Error: CHANGELOG.md file not found" && exit 1)
      
    - name: Verify version on release branches
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        BRANCH_VERSION=$(echo "${{ github.ref_name }}" | sed 's/release\/v//')
        FILE_VERSION=$(cat VERSION)
        if [ "$BRANCH_VERSION" != "$FILE_VERSION" ]; then
          echo "Error: Branch version ($BRANCH_VERSION) does not match VERSION file ($FILE_VERSION)"
          exit 1
        fi